server:
  port: 7531
  servlet:
    context-path: /api
    
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: dev
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gmapi?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # redis config
  redis:
    port: 6379
    host: localhost
    password: 123456
    database: 0
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  rabbitmq:
    host: localhost
    virtual-host: / # 虚拟主机
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual #手动确认接收到的消息
        prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一个消息

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

dubbo:
  application:
    name: gmapi-third-party-provider
  consumer:
    timeout: 3000
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848

# 支付宝沙箱
alipay:
  appId: 
  appPrivateKey: 
  alipayPublicKey:
  notifyUrl: 
  
# 阿里云 SMS 配置
alisms:
  accessKeyId: 
  accessKeySecret: 
  signName: 
  templateCode: 